"""Fix UserPack model

Revision ID: 17a9ffe07f03
Revises: 308366cb44aa
Create Date: 2015-07-19 20:15:25.935029

"""

# revision identifiers, used by Alembic.
revision = '17a9ffe07f03'
down_revision = '308366cb44aa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pack',
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['pack.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('pack_id', 'user_id')
    )
    op.drop_table('user_packs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_packs',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pack_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], [u'pack.id'], name=u'user_packs_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.account_id'], name=u'user_packs_ibfk_2'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('user_pack')
    ### end Alembic commands ###
