"""Added charm and packs models

Revision ID: 25a6ee21577d
Revises: 39b445a33319
Create Date: 2015-07-18 15:56:22.486901

"""

# revision identifiers, used by Alembic.
revision = '25a6ee21577d'
down_revision = '39b445a33319'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('hero', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['pack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charm')
    op.drop_table('pack')
    ### end Alembic commands ###
