"""Add ti5 ticket status

Revision ID: 3f4d38db0caf
Revises: 25a6ee21577d
Create Date: 2015-07-19 17:54:55.066105

"""

# revision identifiers, used by Alembic.
revision = '3f4d38db0caf'
down_revision = '25a6ee21577d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ti5_ticket', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ti5_ticket')
    ### end Alembic commands ###
