"""Add email column to users

Revision ID: 475a20af2e75
Revises: 17a9ffe07f03
Create Date: 2015-07-27 20:29:38.844920

"""

# revision identifiers, used by Alembic.
revision = '475a20af2e75'
down_revision = '17a9ffe07f03'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=256, collation='utf8_swedish_ci'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###
